/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedConfigurationRouteImport } from './routes/_authenticated/configuration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEngineRegistrationRouteImport } from './routes/_authenticated/engine-registration'
import { Route as AuthenticatedExecutionProfilesRouteImport } from './routes/_authenticated/execution-profiles'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedMarketsRouteImport } from './routes/_authenticated/markets'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOwnershipRouteImport } from './routes/_authenticated/ownership'
import { Route as AuthenticatedReplayRouteImport } from './routes/_authenticated/replay'
import { Route as AuthenticatedSignalTankRouteImport } from './routes/_authenticated/signal-tank'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedTradeMonitorRouteImport } from './routes/_authenticated/trade-monitor'
import { Route as AuthenticatedWindowsRouteImport } from './routes/_authenticated/windows'
import { Route as ApiPublicAuthorityConfigurationRouteImport } from './routes/api/public/authority/configuration'
import { Route as ApiPublicAuthorityHeartbeatRouteImport } from './routes/api/public/authority/heartbeat'
import { Route as ApiPublicAuthorityRegisterRouteImport } from './routes/api/public/authority/register'
import { Route as ApiPublicHealthIndexRouteImport } from './routes/api/public/health/index'
import { Route as ApiPublicHealthDetailsRouteImport } from './routes/api/public/health/details'
import { Route as ApiPublicHealthLiveRouteImport } from './routes/api/public/health/live'
import { Route as ApiPublicHealthReadyRouteImport } from './routes/api/public/health/ready'
import { Route as ApiPublicHealthStartupRouteImport } from './routes/api/public/health/startup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigurationRoute =
  AuthenticatedConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineRegistrationRoute =
  AuthenticatedEngineRegistrationRouteImport.update({
    id: '/engine-registration',
    path: '/engine-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutionProfilesRoute =
  AuthenticatedExecutionProfilesRouteImport.update({
    id: '/execution-profiles',
    path: '/execution-profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketsRoute = AuthenticatedMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnershipRoute = AuthenticatedOwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReplayRoute = AuthenticatedReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignalTankRoute = AuthenticatedSignalTankRouteImport.update({
  id: '/signal-tank',
  path: '/signal-tank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradeMonitorRoute =
  AuthenticatedTradeMonitorRouteImport.update({
    id: '/trade-monitor',
    path: '/trade-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWindowsRoute = AuthenticatedWindowsRouteImport.update({
  id: '/windows',
  path: '/windows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAuthorityConfigurationRoute =
  ApiPublicAuthorityConfigurationRouteImport.update({
    id: '/api/public/authority/configuration',
    path: '/api/public/authority/configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthorityHeartbeatRoute =
  ApiPublicAuthorityHeartbeatRouteImport.update({
    id: '/api/public/authority/heartbeat',
    path: '/api/public/authority/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthorityRegisterRoute =
  ApiPublicAuthorityRegisterRouteImport.update({
    id: '/api/public/authority/register',
    path: '/api/public/authority/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthIndexRoute = ApiPublicHealthIndexRouteImport.update({
  id: '/api/public/health/',
  path: '/api/public/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthDetailsRoute = ApiPublicHealthDetailsRouteImport.update({
  id: '/api/public/health/details',
  path: '/api/public/health/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthLiveRoute = ApiPublicHealthLiveRouteImport.update({
  id: '/api/public/health/live',
  path: '/api/public/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthReadyRoute = ApiPublicHealthReadyRouteImport.update({
  id: '/api/public/health/ready',
  path: '/api/public/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthStartupRoute = ApiPublicHealthStartupRouteImport.update({
  id: '/api/public/health/startup',
  path: '/api/public/health/startup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/configuration': typeof AuthenticatedConfigurationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/engine-registration': typeof AuthenticatedEngineRegistrationRoute
  '/execution-profiles': typeof AuthenticatedExecutionProfilesRoute
  '/health': typeof AuthenticatedHealthRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ownership': typeof AuthenticatedOwnershipRoute
  '/replay': typeof AuthenticatedReplayRoute
  '/signal-tank': typeof AuthenticatedSignalTankRoute
  '/system': typeof AuthenticatedSystemRoute
  '/trade-monitor': typeof AuthenticatedTradeMonitorRoute
  '/windows': typeof AuthenticatedWindowsRoute
  '/api/public/authority/configuration': typeof ApiPublicAuthorityConfigurationRoute
  '/api/public/authority/heartbeat': typeof ApiPublicAuthorityHeartbeatRoute
  '/api/public/authority/register': typeof ApiPublicAuthorityRegisterRoute
  '/api/public/health/details': typeof ApiPublicHealthDetailsRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/health/startup': typeof ApiPublicHealthStartupRoute
  '/api/public/health/': typeof ApiPublicHealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/configuration': typeof AuthenticatedConfigurationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/engine-registration': typeof AuthenticatedEngineRegistrationRoute
  '/execution-profiles': typeof AuthenticatedExecutionProfilesRoute
  '/health': typeof AuthenticatedHealthRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ownership': typeof AuthenticatedOwnershipRoute
  '/replay': typeof AuthenticatedReplayRoute
  '/signal-tank': typeof AuthenticatedSignalTankRoute
  '/system': typeof AuthenticatedSystemRoute
  '/trade-monitor': typeof AuthenticatedTradeMonitorRoute
  '/windows': typeof AuthenticatedWindowsRoute
  '/api/public/authority/configuration': typeof ApiPublicAuthorityConfigurationRoute
  '/api/public/authority/heartbeat': typeof ApiPublicAuthorityHeartbeatRoute
  '/api/public/authority/register': typeof ApiPublicAuthorityRegisterRoute
  '/api/public/health/details': typeof ApiPublicHealthDetailsRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/health/startup': typeof ApiPublicHealthStartupRoute
  '/api/public/health': typeof ApiPublicHealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/configuration': typeof AuthenticatedConfigurationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/engine-registration': typeof AuthenticatedEngineRegistrationRoute
  '/_authenticated/execution-profiles': typeof AuthenticatedExecutionProfilesRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/markets': typeof AuthenticatedMarketsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/ownership': typeof AuthenticatedOwnershipRoute
  '/_authenticated/replay': typeof AuthenticatedReplayRoute
  '/_authenticated/signal-tank': typeof AuthenticatedSignalTankRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/trade-monitor': typeof AuthenticatedTradeMonitorRoute
  '/_authenticated/windows': typeof AuthenticatedWindowsRoute
  '/api/public/authority/configuration': typeof ApiPublicAuthorityConfigurationRoute
  '/api/public/authority/heartbeat': typeof ApiPublicAuthorityHeartbeatRoute
  '/api/public/authority/register': typeof ApiPublicAuthorityRegisterRoute
  '/api/public/health/details': typeof ApiPublicHealthDetailsRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/health/startup': typeof ApiPublicHealthStartupRoute
  '/api/public/health/': typeof ApiPublicHealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit'
    | '/configuration'
    | '/dashboard'
    | '/engine-registration'
    | '/execution-profiles'
    | '/health'
    | '/markets'
    | '/notifications'
    | '/ownership'
    | '/replay'
    | '/signal-tank'
    | '/system'
    | '/trade-monitor'
    | '/windows'
    | '/api/public/authority/configuration'
    | '/api/public/authority/heartbeat'
    | '/api/public/authority/register'
    | '/api/public/health/details'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/health/startup'
    | '/api/public/health/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit'
    | '/configuration'
    | '/dashboard'
    | '/engine-registration'
    | '/execution-profiles'
    | '/health'
    | '/markets'
    | '/notifications'
    | '/ownership'
    | '/replay'
    | '/signal-tank'
    | '/system'
    | '/trade-monitor'
    | '/windows'
    | '/api/public/authority/configuration'
    | '/api/public/authority/heartbeat'
    | '/api/public/authority/register'
    | '/api/public/health/details'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/health/startup'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/configuration'
    | '/_authenticated/dashboard'
    | '/_authenticated/engine-registration'
    | '/_authenticated/execution-profiles'
    | '/_authenticated/health'
    | '/_authenticated/markets'
    | '/_authenticated/notifications'
    | '/_authenticated/ownership'
    | '/_authenticated/replay'
    | '/_authenticated/signal-tank'
    | '/_authenticated/system'
    | '/_authenticated/trade-monitor'
    | '/_authenticated/windows'
    | '/api/public/authority/configuration'
    | '/api/public/authority/heartbeat'
    | '/api/public/authority/register'
    | '/api/public/health/details'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/health/startup'
    | '/api/public/health/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAuthorityConfigurationRoute: typeof ApiPublicAuthorityConfigurationRoute
  ApiPublicAuthorityHeartbeatRoute: typeof ApiPublicAuthorityHeartbeatRoute
  ApiPublicAuthorityRegisterRoute: typeof ApiPublicAuthorityRegisterRoute
  ApiPublicHealthDetailsRoute: typeof ApiPublicHealthDetailsRoute
  ApiPublicHealthLiveRoute: typeof ApiPublicHealthLiveRoute
  ApiPublicHealthReadyRoute: typeof ApiPublicHealthReadyRoute
  ApiPublicHealthStartupRoute: typeof ApiPublicHealthStartupRoute
  ApiPublicHealthIndexRoute: typeof ApiPublicHealthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuration': {
      id: '/_authenticated/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AuthenticatedConfigurationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engine-registration': {
      id: '/_authenticated/engine-registration'
      path: '/engine-registration'
      fullPath: '/engine-registration'
      preLoaderRoute: typeof AuthenticatedEngineRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execution-profiles': {
      id: '/_authenticated/execution-profiles'
      path: '/execution-profiles'
      fullPath: '/execution-profiles'
      preLoaderRoute: typeof AuthenticatedExecutionProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markets': {
      id: '/_authenticated/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AuthenticatedMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ownership': {
      id: '/_authenticated/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof AuthenticatedOwnershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/replay': {
      id: '/_authenticated/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AuthenticatedReplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signal-tank': {
      id: '/_authenticated/signal-tank'
      path: '/signal-tank'
      fullPath: '/signal-tank'
      preLoaderRoute: typeof AuthenticatedSignalTankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade-monitor': {
      id: '/_authenticated/trade-monitor'
      path: '/trade-monitor'
      fullPath: '/trade-monitor'
      preLoaderRoute: typeof AuthenticatedTradeMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/windows': {
      id: '/_authenticated/windows'
      path: '/windows'
      fullPath: '/windows'
      preLoaderRoute: typeof AuthenticatedWindowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/authority/configuration': {
      id: '/api/public/authority/configuration'
      path: '/api/public/authority/configuration'
      fullPath: '/api/public/authority/configuration'
      preLoaderRoute: typeof ApiPublicAuthorityConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/authority/heartbeat': {
      id: '/api/public/authority/heartbeat'
      path: '/api/public/authority/heartbeat'
      fullPath: '/api/public/authority/heartbeat'
      preLoaderRoute: typeof ApiPublicAuthorityHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/authority/register': {
      id: '/api/public/authority/register'
      path: '/api/public/authority/register'
      fullPath: '/api/public/authority/register'
      preLoaderRoute: typeof ApiPublicAuthorityRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/': {
      id: '/api/public/health/'
      path: '/api/public/health'
      fullPath: '/api/public/health/'
      preLoaderRoute: typeof ApiPublicHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/details': {
      id: '/api/public/health/details'
      path: '/api/public/health/details'
      fullPath: '/api/public/health/details'
      preLoaderRoute: typeof ApiPublicHealthDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/live': {
      id: '/api/public/health/live'
      path: '/api/public/health/live'
      fullPath: '/api/public/health/live'
      preLoaderRoute: typeof ApiPublicHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/ready': {
      id: '/api/public/health/ready'
      path: '/api/public/health/ready'
      fullPath: '/api/public/health/ready'
      preLoaderRoute: typeof ApiPublicHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/startup': {
      id: '/api/public/health/startup'
      path: '/api/public/health/startup'
      fullPath: '/api/public/health/startup'
      preLoaderRoute: typeof ApiPublicHealthStartupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConfigurationRoute: typeof AuthenticatedConfigurationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEngineRegistrationRoute: typeof AuthenticatedEngineRegistrationRoute
  AuthenticatedExecutionProfilesRoute: typeof AuthenticatedExecutionProfilesRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedMarketsRoute: typeof AuthenticatedMarketsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOwnershipRoute: typeof AuthenticatedOwnershipRoute
  AuthenticatedReplayRoute: typeof AuthenticatedReplayRoute
  AuthenticatedSignalTankRoute: typeof AuthenticatedSignalTankRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedTradeMonitorRoute: typeof AuthenticatedTradeMonitorRoute
  AuthenticatedWindowsRoute: typeof AuthenticatedWindowsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConfigurationRoute: AuthenticatedConfigurationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEngineRegistrationRoute: AuthenticatedEngineRegistrationRoute,
  AuthenticatedExecutionProfilesRoute: AuthenticatedExecutionProfilesRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedMarketsRoute: AuthenticatedMarketsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOwnershipRoute: AuthenticatedOwnershipRoute,
  AuthenticatedReplayRoute: AuthenticatedReplayRoute,
  AuthenticatedSignalTankRoute: AuthenticatedSignalTankRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedTradeMonitorRoute: AuthenticatedTradeMonitorRoute,
  AuthenticatedWindowsRoute: AuthenticatedWindowsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAuthorityConfigurationRoute: ApiPublicAuthorityConfigurationRoute,
  ApiPublicAuthorityHeartbeatRoute: ApiPublicAuthorityHeartbeatRoute,
  ApiPublicAuthorityRegisterRoute: ApiPublicAuthorityRegisterRoute,
  ApiPublicHealthDetailsRoute: ApiPublicHealthDetailsRoute,
  ApiPublicHealthLiveRoute: ApiPublicHealthLiveRoute,
  ApiPublicHealthReadyRoute: ApiPublicHealthReadyRoute,
  ApiPublicHealthStartupRoute: ApiPublicHealthStartupRoute,
  ApiPublicHealthIndexRoute: ApiPublicHealthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
